name: spartan_score
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  syncfusion_flutter_charts: ^32.2.9
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4  

flutter:
  uses-material-design: true

  assets:
    - assets/Images/logo.png
    - assets/Images/sslogo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Images/logo.png"